### ISSUE TITLE
As a developer, I want to create a presentation slide

### ISSUE THREAD

**Issue by atmoprakash** [sujan-lama/MWA-final-project#15]

**Comment by sujan-lama** [comment]
https://mum0-my.sharepoint.com/:p:/g/personal/gjoshi_miu_edu/EYxTubulRxxGm11ST7izyvYBt3_6Yds9srGAZtiOSCr0cQ?e=4%3AgJfUFD&at=9&CID=838A8E1B-A462-48E4-818E-46B42EE5AB99&wdLOR=cA278EE89-114A-4596-9403-6B7CC7101150
